# import all of Sulley's functionality.
from sulley import *
# does nothing but save greeting message
def get_greeting_msg(sock):
greet_message = sock.recv(10000)
session.log("Greeting Message -->%s" % greet_message, 2)
def callback(session, node, edge, sock):
session.log("Date sent -->%s" % node.render(), 2)
s_initialize("helo")
if s_block_start("helo"):
s_static("helo ")
s_delim(" ")
s_static("test.com")
s_static("\r\n")
s_block_end()
s_initialize("ehlo")
if s_block_start("ehlo"):
s_static("ehlo ")
s_delim(" ")
s_random("xxx.com", 5, 10)
s_static("\r\n")
s_block_end()
s_initialize("mail from")
if s_block_start("mail from"):
s_static("mail from: ")
s_delim("")
s_delim("<")
s_static("haha@ims.com")
s_delim(">")
s_static("\r\n")
#s_random('\x09\x78', min_length=101124, max_length=102219)
s_block_end()
s_initialize("rcpt to")
if s_block_start("rcpt to"):
s_static("RCPT TO")
s_delim(":")
s_static("alice@test.com")
s_static("\r\n")
s_block_end()
s_initialize("pre_data")
if s_block_start("pre_data"):
s_static("DATA\r\n")
s_block_end()
s_initialize("data_content")
if s_block_start("data_content"):
s_static("Received:")
s_string("Whatever")
s_static("\r\n")
s_static("Subject:")
s_string("GOGOGOA"*2)
s_static("\r\n")
s_static("\r\n")
s_string("haha")
s_static("\r\n.\r\n")
s_block_end()
sess = sessions.session(log_level=100)
target = sessions.target("127.0.0.1", 25)
sess.add_target(target)
sess.connect(sess.root, s_get("helo"), callback)
sess.connect(sess.root, s_get("ehlo"), callback)
sess.connect(s_get("helo"), s_get("mail from"), callback)
sess.connect(s_get("ehlo"), s_get("mail from"), callback)
sess.connect(s_get("mail from"), s_get("rcpt to"), callback)
sess.connect(s_get("rcpt to"), s_get("pre_data"), callback)
sess.connect(s_get("pre_data"), s_get("data_content"), callback)
sess.fuzz()
